In [2]:
import pandas as pd
from sqlalchemy import create_engine

In [42]:
csv_file = "../Resources/country_vaccinations.csv"
world_vac_df = pd.read_csv(csv_file)
world_vac_df.sample(5)

,country,iso_code,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million,vaccines,source_name,source_website
1076,Malta,MLT,2021-01-10,NaN,NaN,NaN,NaN,396.0,NaN,NaN,NaN,897.0,Pfizer/BioNTech,Ministry of Health,https://deputyprimeminister.gov.mt/en/health-p...
1722,Switzerland,CHE,2021-01-08,NaN,NaN,NaN,NaN,3000.0,NaN,NaN,NaN,347.0,"Moderna, Pfizer/BioNTech",Federal Office of Public Health,https://www.bag.admin.ch/dam/bag/fr/dokumente/...
1711,Switzerland,CHE,2020-12-28,NaN,NaN,NaN,NaN,3000.0,NaN,NaN,NaN,347.0,"Moderna, Pfizer/BioNTech",Federal Office of Public Health,https://www.bag.admin.ch/dam/bag/fr/dokumente/...
906,Israel,ISR,2021-01-20,3100522.0,2383269.0,717253.0,216309.0,143288.0,35.82,27.53,8.29,16554.0,"Moderna, Pfizer/BioNTech",Government of Israel,https://datadashboard.health.gov.il/COVID-19/g...
610,France,FRA,2021-01-09,86315.0,86315.0,NaN,10293.0,12278.0,0.13,0.13,NaN,181.0,Pfizer/BioNTech,Public Health France,https://www.data.gouv.fr/fr/datasets/donnees-r...

In [43]:
#country,iso_code, date, daily_vaccinations, vaccines,source_name

In [24]:
csv_file = "../Resources/covid_impact_on_airport_traffic.csv"
airport_traffic_df = pd.read_csv(csv_file)
airport_traffic_df.sample(5)

,AggregationMethod,Date,Version,AirportName,PercentOfBaseline,Centroid,City,State,ISO_3166_2,Country,Geography
2566,Daily,9/19/2020,1,Montreal Trudeau,75,POINT(-73.7424121584688 45.4678436940192),Dorval,Quebec,CA-QC,Canada,"POLYGON((-73.751757144928 45.44954912446, -73...."
6777,Daily,10/19/2020,1,Washington Dulles International,71,POINT(-77.4427728838621 38.9475939204352),Floris,Virginia,US-VA,United States of America (the),"POLYGON((-77.4458885192871 38.9760921336351, -..."
3375,Daily,10/5/2020,1,Denver International,70,POINT(-104.700315559089 39.8643468206413),Denver,Colorado,US-CO,United States of America (the),"POLYGON((-104.661254882812 39.8242265704646, -..."
647,Daily,4/4/2020,1,Calgary International,51,POINT(-114.013122872131 51.1184753727795),Calgary,Alberta,CA-AB,Canada,"POLYGON((-113.981866836548 51.1392131913567, -..."
121,Daily,10/17/2020,1,Kingsford Smith,11,POINT(151.180087713813 -33.9459774986125),Sydney,New South Wales,AU,Australia,"POLYGON((151.164354085922 -33.9301772341877, 1..."

In [ ]:
#Date,Country,State,City, AirportName,PercentOfBaseline

In [45]:
csv_file = "../Resources/covid_19_clean_complete.csv"
covid_case_df = pd.read_csv(csv_file)
covid_case_df.sample(5)

,Province/State,Country/Region,Lat,Long,Date,Confirmed,Deaths,Recovered,Active,WHO Region
27858,NaN,Serbia,44.0165,21.0059,2020-05-07,9848,206,2160,7482,Europe
387,NaN,Honduras,15.2000,-86.2419,2020-01-23,0,0,0,0,Americas
47144,Aruba,Netherlands,12.5211,-69.9683,2020-07-20,115,3,100,12,Europe
17803,Guizhou,China,26.8154,106.8748,2020-03-30,146,2,144,0,Western Pacific
21632,NaN,Grenada,12.1165,-61.6790,2020-04-13,14,0,0,14,Americas

In [ ]:
#change the column:Country/Region to Country
#Date,Country,Confirmed,

In [20]:
csv_file = "../Resources/worldometer_data.csv"
worldometer_df = pd.read_csv(csv_file)
worldometer_df.sample(5)

,Country/Region,Continent,Population,TotalCases,NewCases,TotalDeaths,NewDeaths,TotalRecovered,NewRecovered,ActiveCases,"Serious,Critical",Tot Cases/1M pop,Deaths/1M pop,TotalTests,Tests/1M pop,WHO Region
129,Iceland,Europe,341465.0,1930,NaN,10.0,NaN,1825.0,NaN,95.0,NaN,5652.0,29.0,149693.0,438385.0,Europe
127,Guinea-Bissau,Africa,1972277.0,2032,NaN,27.0,NaN,944.0,NaN,1061.0,5.0,1030.0,14.0,1500.0,761.0,Africa
35,Belgium,Europe,11594739.0,71158,NaN,9859.0,NaN,17661.0,NaN,43638.0,61.0,6137.0,850.0,1767120.0,152407.0,Europe
25,Kazakhstan,Asia,18798667.0,95942,NaN,1058.0,NaN,68871.0,NaN,26013.0,221.0,5104.0,56.0,2163713.0,115099.0,Europe
124,Mozambique,Africa,31333962.0,2120,NaN,15.0,NaN,795.0,NaN,1310.0,NaN,68.0,0.5,65151.0,2079.0,Africa